"""MiMo HomeOps Agent Pro — Pydantic models."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


# ── Device Models ──────────────────────────────────────────────────────────

class DeviceType(str, Enum):
    LIGHT = "light"
    AC = "ac"
    FAN = "fan"
    CURTAIN = "curtain"
    PURIFIER = "purifier"
    VACUUM = "vacuum"
    PLUG = "plug"
    SENSOR = "sensor"


class DeviceState(BaseModel):
    """Current state of a device."""
    id: str
    name: str
    room: str
    type: DeviceType
    online: bool = True
    attributes: dict[str, Any] = Field(default_factory=dict)


class DeviceAction(BaseModel):
    """An action to perform on a device."""
    device_id: str
    action: str  # e.g. "light.on", "ac.set_temp"
    parameters: dict[str, Any] = Field(default_factory=dict)
    reason: str = ""
    risk_level: str = "low"  # low, medium, high, critical
    requires_confirmation: bool = False


class ActionPlan(BaseModel):
    """A structured plan generated by MiMo."""
    goal: str
    actions: list[DeviceAction]
    summary: str = ""
    estimated_energy_impact: str = ""


# ── Timeline / History ─────────────────────────────────────────────────────

class TimelineEntry(BaseModel):
    id: int | None = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    device_id: str
    device_name: str
    action: str
    before_state: dict[str, Any] = Field(default_factory=dict)
    after_state: dict[str, Any] = Field(default_factory=dict)
    explanation: str = ""
    risk_level: str = "low"
    executed: bool = True


# ── Automation Rules ────────────────────────────────────────────────────────

class AutomationCondition(BaseModel):
    field: str  # e.g. "bedroom.temperature", "time", "bedroom.motion"
    operator: str  # ">", "<", ">=", "<=", "==", "!="
    value: Any


class AutomationAction(BaseModel):
    device_id: str
    action: str
    parameters: dict[str, Any] = Field(default_factory=dict)


class AutomationRule(BaseModel):
    id: str | None = None
    name: str
    enabled: bool = True
    conditions: list[AutomationCondition]
    actions: list[AutomationAction]
    reason: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── Incident ────────────────────────────────────────────────────────────────

class IncidentSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Incident(BaseModel):
    id: int | None = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    severity: IncidentSeverity
    title: str
    description: str
    device_id: str | None = None
    resolved: bool = False


# ── Reports ─────────────────────────────────────────────────────────────────

class EnergyReport(BaseModel):
    date: str
    active_devices: int
    comfort_score: float  # 0-100
    energy_waste_alerts: list[str] = Field(default_factory=list)
    savings_summary: str = ""
    suggested_automations: list[str] = Field(default_factory=list)


# ── API Request / Response ──────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message: str
    dry_run: bool = True
    confirm: bool = False


class ChatResponse(BaseModel):
    reply: str
    plan: ActionPlan | None = None
    timeline_entries: list[TimelineEntry] = Field(default_factory=list)
    needs_confirmation: bool = False


class HealthResponse(BaseModel):
    status: str = "ok"
    version: str = "0.1.0"
    uptime_seconds: float = 0
    device_count: int = 0
